#se compila siempre el archivo x86 primero ya que contiene la entrada a main()
OBJ := $(OBJ) core/kernel.o $(OBJ) core/process.o core/diskpartition.o core/filesystem.o \
	core/elfloader.o core/systemcall.o \
	core/adminProcess.o core/file.o core/exclusion.o core/cacheDisk.o \
	core/thread.o core/pioscreen.o core/devices.o core/graphics.o 