#se compila siempre el archivo x86 primero ya que contiene la entrada a main()
OBJ := $(OBJ) drivers/diskide.o drivers/vga.o drivers/vga/registerVGA.o drivers/vga/videomode/mode320x200x256.o  \
	drivers/vga/videomode/modetext80x25x16.o drivers/vga/font/lucidaconsole.o drivers/vga/font/systembyte.o \
	drivers/vga/palette/palette256.o drivers/cdide.o drivers/mouse.o drivers/keyborad.o \
	drivers/clock.o drivers/bxvga.o drivers/pci.o drivers/vga/videomode/mode720x480x4.o drivers/vga/font/basic.o